### ISSUE TITLE
Manifest/EXE mismatch error.

### ISSUE THREAD

**Issue by gamax92** [gamax92/wine-overwatch-new#1]
old wine-overwatch 2.3 and the new wine-overwatch 2.4 give this "Manifest/EXE mismatch." error when booting up. Investigating, seems to be an issue with bcrypt.dll ...

If possible, report if you're having this issue too

**Comment by gamax92** [comment]
Fixed by partially implementing BCryptImportKey

**Comment by RalphMalph** [comment]
Hi gamax.
Would you please explain how you did this fix in as much detail as possible? (I've just recently switched to Linux from Windows and am still learning.) Anyway, I'm getting the same error as you did when I press Overwatch game's PLAY button on Blizzard after installing via Lutris. Thanks in advance, Ralph

**Comment by gamax92** [comment]
Sorry can't. Here's the commit: d9cad724d72ab062eb6c46e9d3309df25223d260
I don't understand it myself.
Don't bother trying to use this repo, it doesn't work anymore.
